//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.21 at 04:32:57 �U�� TST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tssco.com/restful/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.codingfun.restful.xsd;
